version: '3.8'
services:
  app:
    image: falseviking/studymap-planner-front:latest  # Replace with your actual Docker Hub username and correct tag
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: rootyroot
      DATABASE_NAME: users
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootyroot
      MYSQL_DATABASE: users
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
