name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: h0bbitten/StudymapPlannerFront  # Update repository URL
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
       run: echo "//docker.io/v1/ ${secrets.dckr_pat_ujusRPRBe8NQDOurA7HN85G2K2E }}" | docker login -u falseviking --password-stdin

      
    - name: Build and push Docker image
      run: |
        docker buildx build --platform windows/amd64 -t falseviking/studymap-planner-front:latest . --push