name: Docker Build and Push

on:
  push:
    branches:
      - Docker-Connection

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "dckr_pat_ujusRPRBe8NQDOurA7HN85G2K2E" | docker login -u falseviking --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t falseviking/studymap-planner-front:latest . --push

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Deploy using Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Verify Deployment
      run: |
        docker-compose ps